<x-admin>
    
    <script>
        $("#dashboard-link").addClass("active");
    </script>

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum vel ligula eu sapien porttitor semper vel a nibh. In quis urna feugiat, blandit purus vel, elementum nunc. Donec ullamcorper, nunc vitae sollicitudin finibus, urna urna congue urna, vel mollis erat felis nec massa. Etiam iaculis suscipit consequat. Mauris posuere, libero non dapibus aliquam, ex mauris lobortis odio, et porta nibh quam sit amet justo. Ut malesuada diam sit amet porta malesuada. Suspendisse condimentum, risus ornare fermentum dictum, risus lectus feugiat velit, at maximus ipsum tellus eget purus. Nunc tincidunt ex pretium lobortis tristique.

Suspendisse tincidunt urna at ligula rhoncus fringilla. Donec eu ligula euismod, condimentum turpis eget, convallis massa. In hac habitasse platea dictumst. Sed leo lectus, luctus sed diam vitae, faucibus aliquet massa. Aliquam feugiat metus id aliquam consectetur. Sed purus erat, finibus eget justo a, gravida vulputate justo. Donec venenatis turpis eu quam vehicula fermentum. Suspendisse auctor erat a nunc blandit aliquam. Suspendisse ut sagittis turpis. Vestibulum iaculis neque eget urna congue elementum. Nullam vestibulum tempus lorem, vel placerat leo condimentum eu. Fusce eu nisi sit amet nulla malesuada finibus et condimentum metus.

In sit amet orci ex. Maecenas eget augue non elit semper maximus. Curabitur convallis magna ac diam feugiat, in bibendum tortor ullamcorper. Ut ut porta nulla. Nulla facilisi. In mi turpis, convallis quis faucibus vitae, iaculis dictum elit. Suspendisse bibendum elementum lorem nec consequat. Aliquam sit amet ullamcorper felis. Aenean elementum ligula nec turpis ullamcorper, ultrices rhoncus enim vehicula. Aliquam convallis, nisl sit amet tincidunt luctus, ligula enim bibendum dui, sit amet auctor dolor justo nec quam. Curabitur vel dapibus diam. Integer nec lobortis ex. Aliquam dapibus ipsum orci, eu ultrices augue posuere in. Suspendisse varius, massa ac sagittis sagittis, eros urna fringilla nunc, non varius ipsum eros at ex.

Vestibulum dignissim odio ut auctor aliquet. Phasellus porttitor id enim in tempus. Aenean gravida tellus sit amet laoreet posuere. Nunc suscipit porttitor lectus, et tempor arcu venenatis sed. Aenean finibus finibus arcu eu vehicula. Curabitur vel ante diam. Praesent ultrices magna arcu. Etiam eu posuere lectus. Nunc ac nisl libero.

Integer dolor ligula, scelerisque at tincidunt ac, euismod vel lorem. Integer a est sit amet ex elementum pretium sit amet sit amet lacus. Fusce iaculis nisl erat, varius laoreet nunc laoreet sed. Sed non porta metus. Maecenas in magna at urna accumsan dictum ut sed nulla. Nam vel viverra nisi, non efficitur ante. Nullam dui arcu, dapibus id elit nec, mattis feugiat dui. Nullam arcu eros, sollicitudin eu pharetra ac, fermentum sit amet tellus. Sed dictum et eros et consectetur. Donec volutpat finibus lacus, a porttitor lorem feugiat id. Vivamus fermentum justo sit amet ligula blandit porttitor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In hac habitasse platea dictumst. Integer leo elit, vestibulum eget felis et, sodales convallis felis. Integer vitae molestie diam.

Vivamus non erat quis nibh semper rutrum. Aliquam erat volutpat. In in felis quis ipsum tincidunt viverra. Integer non pretium augue. Nunc vulputate, nisi et sodales congue, lectus dui feugiat nisi, nec lobortis sem elit vel nibh. Suspendisse quis tortor dapibus, suscipit erat in, gravida lorem. Donec tellus dui, rutrum in ultrices volutpat, finibus ac velit. Vivamus euismod nisi quis ligula aliquam bibendum. Donec aliquam id urna et venenatis. Etiam accumsan imperdiet nulla at euismod. Nulla ut urna ornare, ultricies metus in, consectetur nunc. Aenean sapien quam, iaculis a rutrum fermentum, accumsan ac leo. Phasellus sit amet arcu ut lorem efficitur sollicitudin id in massa.

Maecenas sed lacus non tortor sollicitudin commodo in quis arcu. Aliquam quis mi non dolor dictum ullamcorper. Suspendisse potenti. Duis quis aliquet lacus, non vehicula odio. Vivamus vel orci vitae nulla accumsan pellentesque eget sit amet justo. Suspendisse sit amet mollis arcu, ut tristique lectus. Ut eu nisi rutrum risus rutrum interdum. Nunc gravida sit amet nunc eget scelerisque. In sollicitudin placerat congue. Nulla gravida augue eu dui hendrerit efficitur. Morbi id est sit amet odio egestas iaculis non tincidunt massa. Maecenas nec mollis lectus. Maecenas nec ipsum tempor, vehicula diam in, egestas sem.

Morbi augue ligula, condimentum vel convallis quis, ultrices gravida justo. Pellentesque cursus sem id ante auctor gravida. Phasellus in imperdiet tortor, sit amet congue arcu. Cras ex quam, molestie et commodo vel, hendrerit nec neque. In vestibulum, nulla eget maximus vulputate, lectus nisl commodo libero, quis feugiat nisi enim vitae nunc. Aliquam odio lacus, vulputate ac egestas vitae, molestie ut metus. Donec euismod lacus id sapien pretium, vitae vehicula massa placerat. Quisque sit amet ligula non magna mattis aliquam non eget sapien. In fermentum blandit tincidunt. Sed est lorem, scelerisque non augue id, finibus commodo orci. Praesent interdum ante ligula, a bibendum leo viverra non. Phasellus erat eros, maximus a convallis vel, pretium vel sem.

Sed id posuere metus. Praesent maximus libero eu velit lacinia luctus. Fusce nec nibh nibh. Duis nisi orci, ornare quis leo ut, sollicitudin tincidunt libero. Vivamus cursus ligula venenatis erat elementum, at dictum libero volutpat. Suspendisse accumsan non sapien et condimentum. Sed imperdiet in magna a suscipit. Pellentesque ut lorem ultrices, dignissim lorem sit amet, sodales sem. Nulla quis fringilla tortor. Nulla cursus, tortor in congue tempus, arcu est congue quam, quis finibus erat purus vitae ligula. Nulla facilisi. Pellentesque efficitur varius sem, sed posuere diam cursus eu. Suspendisse nec faucibus ex. Nullam auctor non felis sit amet consectetur.

Suspendisse accumsan elit a vehicula mattis. Nam auctor accumsan ex eu consequat. Donec convallis ornare ante ut vulputate. Donec commodo lacinia metus consequat convallis. Nullam ornare non tellus eu porta. Phasellus dignissim lacinia efficitur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras sed odio scelerisque, ornare justo ut, cursus nisl. Nullam in nibh lacus. Ut tincidunt quam mattis tortor efficitur auctor. Integer vehicula in nulla eget semper.

Mauris imperdiet orci eu consectetur convallis. Sed purus dui, vehicula eu dictum vel, bibendum sit amet sapien. Integer pellentesque tempus ipsum, quis vehicula tortor tristique sed. Pellentesque faucibus ipsum id elit tincidunt, non convallis lorem tempor. Integer quis libero lectus. Vivamus cursus quis urna in pharetra. Praesent laoreet nisi sit amet rhoncus tincidunt. Donec quis posuere dolor, a mollis sapien. Suspendisse varius, libero quis convallis venenatis, nunc tortor malesuada lorem, eu venenatis neque dolor ac eros. In imperdiet arcu ac massa ullamcorper hendrerit.

Sed pretium ligula sit amet condimentum mollis. Maecenas imperdiet vulputate justo, quis finibus felis luctus nec. Vivamus a augue sapien. Aliquam eu lectus vel lacus vestibulum volutpat id sit amet nunc. In nec libero non neque viverra luctus quis vel tortor. Sed ultricies fermentum neque in sodales. Curabitur posuere risus eget sapien rhoncus maximus. Morbi venenatis risus et facilisis placerat. Suspendisse non condimentum risus. Phasellus sit amet tempus diam. Proin volutpat lobortis lacus quis condimentum. Fusce nec ligula sit amet tortor vehicula imperdiet eget quis lorem.

Etiam pharetra sodales metus nec pulvinar. Integer mattis sem vitae metus feugiat, ac gravida neque tincidunt. Fusce molestie elit quis varius blandit. Aliquam ultricies ex purus, non cursus velit fringilla ornare. Praesent dapibus sed ante id egestas. Suspendisse et odio a lacus egestas ullamcorper. Praesent magna nunc, dictum nec metus nec, aliquam varius ligula. In tempor accumsan leo, a malesuada felis tincidunt a. Donec ut auctor nisi.

Nullam in lobortis lorem. Proin maximus lorem faucibus sapien mollis, vitae lacinia arcu dignissim. Duis nec orci sit amet nunc condimentum imperdiet. Integer luctus quam ex, ut elementum est porttitor eget. Fusce id leo in turpis pretium consectetur. Pellentesque rutrum dui massa, a pellentesque mauris ornare vitae. Maecenas eu mi quis ex sollicitudin aliquam. Morbi in turpis et ante cursus euismod sit amet in enim. Cras blandit tortor leo, ultricies pretium tortor egestas sed. Integer nibh nunc, faucibus tincidunt consectetur vitae, posuere at tortor. Integer eros tellus, scelerisque non est id, porttitor vulputate nulla. Sed condimentum augue sit amet felis viverra ornare. Pellentesque interdum sem nec mauris ullamcorper aliquam.

Proin ullamcorper volutpat semper. Nulla ultrices orci sit amet lacus accumsan maximus. Duis luctus odio nec ligula accumsan bibendum. Mauris fringilla eu eros sit amet gravida. Donec ligula nunc, vestibulum vel leo nec, hendrerit suscipit urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi placerat sem eu lacus commodo elementum. Sed volutpat congue risus, aliquam scelerisque purus ultrices vel.

Curabitur in magna mi. Duis eleifend convallis vulputate. Sed orci ligula, facilisis eu sapien et, sollicitudin pellentesque sapien. Vivamus non enim in odio consequat auctor. Proin scelerisque aliquam felis sed aliquam. Integer consectetur facilisis enim et mollis. Etiam non mi iaculis, tempus urna eget, luctus arcu. In id volutpat mauris. Sed feugiat, diam eget sodales accumsan, nisl mauris scelerisque lacus, in mollis justo ligula ut lorem. Nam egestas ligula at augue accumsan pretium. Nam gravida aliquam quam non lobortis.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam eu ligula lectus. Aenean bibendum tempor faucibus. Nullam eget auctor velit. Proin non pulvinar justo. Proin mattis at eros et feugiat. Phasellus ullamcorper sapien in pretium fringilla. Etiam vestibulum tortor id metus molestie mattis.

Praesent ornare sodales justo a placerat. Vivamus placerat libero sit amet quam consequat, ut dictum lectus placerat. Donec malesuada tortor dolor, et finibus tellus pellentesque sed. Nunc neque odio, sagittis eget luctus sed, facilisis sit amet metus. Praesent scelerisque pharetra nulla in gravida. Fusce vehicula, orci a semper tempus, metus arcu mollis mauris, in pulvinar sem odio quis orci. Ut placerat felis eu semper euismod. Aliquam eget bibendum orci, eu vestibulum nisi. Cras non iaculis ante. Proin eleifend mi tellus, at dignissim nisl hendrerit nec. Suspendisse a euismod massa, a pretium erat.

Morbi sit amet velit at diam consequat luctus. In fringilla nibh vel eros varius euismod. Morbi eu fringilla nisi, eget pharetra leo. Vestibulum accumsan quis turpis vel euismod. Morbi at tristique arcu, et imperdiet justo. Quisque vehicula urna justo, dapibus consequat arcu blandit nec. Aenean mollis porttitor lectus in bibendum. Fusce urna arcu, tempus sed pellentesque quis, cursus at dolor. Mauris eget viverra orci, at faucibus tellus. Maecenas consectetur sapien dolor, in dignissim magna suscipit eget. In non vulputate mi. Etiam interdum sem magna. Donec nec augue magna. Aliquam ac nulla blandit, iaculis nibh eleifend, dignissim odio. Cras porta dui eget nisi lobortis, ut congue sapien dignissim.

Aenean euismod nec neque sed condimentum. Suspendisse sit amet blandit nisi, quis suscipit metus. In hac habitasse platea dictumst. Cras ut pharetra orci. Nullam non cursus nisl, ut tincidunt felis. Fusce fringilla congue lacus eu mollis. Mauris vitae ultrices lacus. In hac habitasse platea dictumst. Fusce et nisi eu dolor vulputate dapibus nec in orci. Pellentesque malesuada velit id lectus blandit, ut tempor metus porttitor. Aenean molestie lacus justo. Cras malesuada enim volutpat imperdiet pharetra. Pellentesque sagittis tortor magna, in malesuada est placerat id. Nam eget molestie risus, eget ultricies quam. Aenean luctus magna non dolor egestas consectetur.

</x-admin>